# Generated by Django 5.1.1 on 2024-12-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_content_event_resource_userprofile_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='video',
            field=models.FileField(default='default_video.mp4', upload_to='videos/'),
        ),
    ]
